/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Result_6 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const DexSource = IDL.Variant({
  'icpSwap' : IDL.Null,
  'sonic' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'closed' : IDL.Null,
  'cancelled' : IDL.Null,
  'open' : IDL.Null,
  'filled' : IDL.Null,
  'liquidated' : IDL.Null,
  'pendingFill' : IDL.Null,
});
export const TradeSide = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
export const Position = IDL.Record({
  'dex' : DexSource,
  'status' : OrderStatus,
  'exitTime' : IDL.Opt(IDL.Int),
  'traderId' : IDL.Principal,
  'currentPrice' : IDL.Float64,
  'direction' : TradeSide,
  'entryTime' : IDL.Int,
  'takeProfit' : IDL.Opt(IDL.Float64),
  'pair' : IDL.Text,
  'size' : IDL.Float64,
  'tradeId' : IDL.Nat,
  'realizedPnl' : IDL.Float64,
  'stopLoss' : IDL.Opt(IDL.Float64),
  'entryPrice' : IDL.Float64,
  'unrealizedPnl' : IDL.Float64,
  'simulatedFill' : IDL.Bool,
});
export const Result_9 = IDL.Variant({ 'ok' : Position, 'err' : IDL.Text });
export const PhaseParams = IDL.Record({
  'timeLimitDays' : IDL.Nat,
  'maxTotalDrawdown' : IDL.Float64,
  'minTradingDays' : IDL.Nat,
  'profitTarget' : IDL.Float64,
  'maxDailyDrawdown' : IDL.Float64,
  'minConsistencyScore' : IDL.Float64,
});
export const CohortParams = IDL.Record({
  'id' : IDL.Nat,
  'active' : IDL.Bool,
  'modifiedBy' : IDL.Opt(IDL.Principal),
  'name' : IDL.Text,
  'createdDate' : IDL.Int,
  'lastModified' : IDL.Int,
  'phase1' : PhaseParams,
  'phase2' : PhaseParams,
});
export const Result_2 = IDL.Variant({ 'ok' : CohortParams, 'err' : IDL.Text });
export const Result_21 = IDL.Variant({
  'ok' : IDL.Record({ 'shares' : IDL.Nat, 'poolBalance' : IDL.Float64 }),
  'err' : IDL.Text,
});
export const RiskLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const ChallengeStatus = IDL.Variant({
  'active' : IDL.Null,
  'failed' : IDL.Null,
  'passed' : IDL.Null,
  'paused' : IDL.Null,
});
export const ChallengePhase = IDL.Variant({
  'notStarted' : IDL.Null,
  'funded' : IDL.Null,
  'phase1' : IDL.Null,
  'phase2' : IDL.Null,
});
export const Challenge = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Int,
  'status' : ChallengeStatus,
  'currentBalance' : IDL.Float64,
  'trades' : IDL.Vec(IDL.Nat),
  'phase2StartTime' : IDL.Opt(IDL.Int),
  'perTradeLimitPct' : IDL.Float64,
  'dailyDrawdownLimitPct' : IDL.Float64,
  'fundedAllocation' : IDL.Opt(IDL.Float64),
  'traderPrincipal' : IDL.Principal,
  'phase1StartTime' : IDL.Opt(IDL.Int),
  'phase1EndTime' : IDL.Opt(IDL.Int),
  'startingBalance' : IDL.Float64,
  'targetProfitPct' : IDL.Float64,
  'phase' : ChallengePhase,
  'totalDrawdownLimitPct' : IDL.Float64,
  'phase2EndTime' : IDL.Opt(IDL.Int),
  'riskLevel' : RiskLevel,
  'consistencyScore' : IDL.Float64,
  'cohortId' : IDL.Opt(IDL.Nat),
});
export const Result_16 = IDL.Variant({ 'ok' : Challenge, 'err' : IDL.Text });
export const ExecutionType = IDL.Variant({
  'simulated' : IDL.Null,
  'real' : IDL.Null,
});
export const Trade = IDL.Record({
  'id' : IDL.Nat,
  'pnl' : IDL.Float64,
  'pair' : IDL.Text,
  'side' : TradeSide,
  'traderPrincipal' : IDL.Principal,
  'fillPrice' : IDL.Float64,
  'timestamp' : IDL.Int,
  'txHash' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Float64,
  'riskCheckPassed' : IDL.Bool,
  'executionType' : ExecutionType,
});
export const Result_20 = IDL.Variant({ 'ok' : Trade, 'err' : IDL.Text });
export const AdminParams = IDL.Record({
  'challengeCheckIntervalSecs' : IDL.Nat,
  'pricePollingIntervalSecs' : IDL.Nat,
  'baseFee' : IDL.Float64,
  'maxTraderSharePct' : IDL.Float64,
  'perTradeLimitPct' : IDL.Float64,
  'dailyDrawdownLimitPct' : IDL.Float64,
  'baseAllocationAmount' : IDL.Float64,
  'updatedAt' : IDL.Int,
  'platformFeePct' : IDL.Float64,
  'investorPoolSharePct' : IDL.Float64,
  'traderBaseSharePct' : IDL.Float64,
  'targetProfitPct' : IDL.Float64,
  'slCheckIntervalSecs' : IDL.Nat,
  'tradingPaused' : IDL.Bool,
  'totalDrawdownLimitPct' : IDL.Float64,
  'riskLevel' : RiskLevel,
  'defaultPhase1' : PhaseParams,
  'defaultPhase2' : PhaseParams,
  'maxAllocationCap' : IDL.Float64,
  'performanceFee' : IDL.Float64,
});
export const AuditEntry = IDL.Record({
  'principal' : IDL.Principal,
  'action' : IDL.Text,
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
});
export const ConsistencyScore = IDL.Record({
  'traderId' : IDL.Principal,
  'activityScore' : IDL.Float64,
  'score' : IDL.Float64,
  'winRateScore' : IDL.Float64,
  'timestamp' : IDL.Int,
  'phase' : ChallengePhase,
  'profitDistScore' : IDL.Float64,
  'drawdownCtrlScore' : IDL.Float64,
});
export const Result_19 = IDL.Variant({
  'ok' : IDL.Record({
    'investorCount' : IDL.Nat,
    'poolBalance' : IDL.Float64,
    'platformFeeBalance' : IDL.Float64,
    'totalShares' : IDL.Nat,
  }),
  'err' : IDL.Text,
});
export const InvestorStats = IDL.Record({
  'totalAllocated' : IDL.Float64,
  'ytdReturn' : IDL.Float64,
  'traderCount' : IDL.Nat,
  'poolBalance' : IDL.Float64,
  'monthlyReturn' : IDL.Float64,
  'weeklyReturn' : IDL.Float64,
  'fundedTraderCount' : IDL.Nat,
  'avgConsistency' : IDL.Float64,
});
export const Result_18 = IDL.Variant({
  'ok' : InvestorStats,
  'err' : IDL.Text,
});
export const LeaderboardEntry = IDL.Record({
  'traderId' : IDL.Principal,
  'username' : IDL.Text,
  'lastTradeTime' : IDL.Int,
  'tradeCount' : IDL.Nat,
  'rank' : IDL.Nat,
  'profitPct' : IDL.Float64,
  'funded' : IDL.Bool,
  'phase' : ChallengePhase,
  'riskScore' : IDL.Float64,
  'consistencyScore' : IDL.Float64,
});
export const PriceData = IDL.Record({
  'source' : IDL.Text,
  'pair' : IDL.Text,
  'timestamp' : IDL.Int,
  'price' : IDL.Float64,
});
export const Result_17 = IDL.Variant({ 'ok' : PriceData, 'err' : IDL.Text });
export const Result_15 = IDL.Variant({
  'ok' : ConsistencyScore,
  'err' : IDL.Text,
});
export const FundedAccount = IDL.Record({
  'traderId' : IDL.Principal,
  'monthsActive' : IDL.Nat,
  'accountBalance' : IDL.Float64,
  'performanceMultiplier' : IDL.Float64,
  'unrealizedPnl' : IDL.Float64,
  'nextReviewDate' : IDL.Int,
  'allocationCurrent' : IDL.Float64,
  'lastReviewDate' : IDL.Int,
  'allocationBase' : IDL.Float64,
});
export const Result_14 = IDL.Variant({
  'ok' : FundedAccount,
  'err' : IDL.Text,
});
export const Result_13 = IDL.Variant({
  'ok' : IDL.Record({
    'sharePrice' : IDL.Float64,
    'poolValue' : IDL.Float64,
    'shares' : IDL.Nat,
    'poolBalance' : IDL.Float64,
    'totalShares' : IDL.Nat,
  }),
  'err' : IDL.Text,
});
export const Result_12 = IDL.Variant({
  'ok' : IDL.Record({
    'consistencyProgress' : IDL.Float64,
    'phase' : ChallengePhase,
    'timeRemainingDays' : IDL.Int,
    'profitProgress' : IDL.Float64,
  }),
  'err' : IDL.Text,
});
export const TraderMode = IDL.Variant({
  'evaluation' : IDL.Null,
  'funded' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'trader' : IDL.Null,
});
export const TraderProfile = IDL.Record({
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'mode' : TraderMode,
  'role' : UserRole,
  'fundedAccount' : IDL.Opt(FundedAccount),
  'activeChallengeId' : IDL.Opt(IDL.Nat),
  'tenureMonths' : IDL.Nat,
  'totalPayouts' : IDL.Float64,
});
export const Result_8 = IDL.Variant({ 'ok' : TraderProfile, 'err' : IDL.Text });
export const PayoutRecord = IDL.Record({
  'status' : IDL.Text,
  'traderId' : IDL.Principal,
  'closeTime' : IDL.Int,
  'consistencyBonus' : IDL.Float64,
  'platformShare' : IDL.Float64,
  'tenureBonus' : IDL.Float64,
  'traderPct' : IDL.Float64,
  'traderShare' : IDL.Float64,
  'investorShare' : IDL.Float64,
  'tradeId' : IDL.Nat,
  'profitAmount' : IDL.Float64,
});
export const Result_11 = IDL.Variant({
  'ok' : IDL.Record({
    'totalPlatformRevenue' : IDL.Float64,
    'totalInvestorPayouts' : IDL.Float64,
    'totalTraderPayouts' : IDL.Float64,
    'platformFeeBalance' : IDL.Float64,
    'investorPoolBalance' : IDL.Float64,
  }),
  'err' : IDL.Text,
});
export const PriceCache = IDL.Record({
  'ask' : IDL.Float64,
  'bid' : IDL.Float64,
  'dex' : DexSource,
  'last' : IDL.Float64,
  'pair' : IDL.Text,
  'volume' : IDL.Float64,
  'stale' : IDL.Bool,
  'timestamp' : IDL.Int,
});
export const TargetOutcome = IDL.Record({
  'consistencyTarget' : IDL.Float64,
  'actualPassRate' : IDL.Float64,
  'lastUpdated' : IDL.Int,
  'passRateTarget' : IDL.Float64,
  'returnTarget' : IDL.Float64,
  'actualReturn' : IDL.Float64,
  'actualConsistency' : IDL.Float64,
  'cohortId' : IDL.Nat,
});
export const Result_5 = IDL.Variant({ 'ok' : TargetOutcome, 'err' : IDL.Text });
export const AllocationChange = IDL.Record({
  'oldAllocation' : IDL.Float64,
  'traderId' : IDL.Principal,
  'reviewedBy' : IDL.Opt(IDL.Principal),
  'newAllocation' : IDL.Float64,
  'timestamp' : IDL.Int,
  'reason' : IDL.Text,
});
export const Result_10 = IDL.Variant({
  'ok' : IDL.Record({
    'multiplier' : IDL.Float64,
    'base' : IDL.Float64,
    'history' : IDL.Vec(AllocationChange),
    'current' : IDL.Float64,
  }),
  'err' : IDL.Text,
});
export const Result_7 = IDL.Variant({ 'ok' : AdminParams, 'err' : IDL.Text });
export const Result_4 = IDL.Variant({
  'ok' : IDL.Vec(
    IDL.Record({
      'metric' : IDL.Text,
      'suggested' : IDL.Float64,
      'current' : IDL.Float64,
      'reason' : IDL.Text,
    })
  ),
  'err' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const Result_3 = IDL.Variant({
  'ok' : IDL.Record({
    'reviewedCount' : IDL.Nat,
    'changes' : IDL.Vec(AllocationChange),
  }),
  'err' : IDL.Text,
});
export const ValidationStatus = IDL.Variant({
  'conditional' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ValidationResult = IDL.Record({
  'status' : ValidationStatus,
  'reasons' : IDL.Vec(IDL.Text),
  'estimatedImpact' : IDL.Float64,
});
export const Result_1 = IDL.Variant({
  'ok' : IDL.Record({ 'remainingShares' : IDL.Nat, 'withdrawn' : IDL.Float64 }),
  'err' : IDL.Text,
});
export const Result = IDL.Variant({ 'ok' : IDL.Float64, 'err' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'cancelOrder' : IDL.Func([IDL.Nat], [Result_6], []),
  'closePosition' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Float64)], [Result_9], []),
  'createCohort' : IDL.Func(
      [IDL.Text, PhaseParams, PhaseParams],
      [Result_2],
      [],
    ),
  'depositToPool' : IDL.Func([IDL.Float64], [Result_21], []),
  'enterChallenge' : IDL.Func(
      [IDL.Float64, IDL.Float64, RiskLevel],
      [Result_16],
      [],
    ),
  'executeTrade' : IDL.Func(
      [IDL.Nat, IDL.Text, TradeSide, IDL.Float64],
      [Result_20],
      [],
    ),
  'forceChallenge' : IDL.Func(
      [IDL.Nat, ChallengeStatus, IDL.Text],
      [Result_16],
      [],
    ),
  'getAdminParams' : IDL.Func([], [AdminParams], ['query']),
  'getAllChallenges' : IDL.Func([], [IDL.Vec(Challenge)], ['query']),
  'getAllCohorts' : IDL.Func([], [IDL.Vec(CohortParams)], ['query']),
  'getAuditLog' : IDL.Func([IDL.Nat], [IDL.Vec(AuditEntry)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getConsistencyScoreHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ConsistencyScore)],
      ['query'],
    ),
  'getFundedTraderList' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'status' : IDL.Text,
            'traderId' : IDL.Principal,
            'username' : IDL.Text,
            'monthlyReturn' : IDL.Float64,
            'allocation' : IDL.Float64,
            'consistencyScore' : IDL.Float64,
          })
        ),
      ],
      ['query'],
    ),
  'getInvestorPoolSummary' : IDL.Func([], [Result_19], ['query']),
  'getInvestorStats' : IDL.Func([], [Result_18], ['query']),
  'getLeaderboard' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getLivePrice' : IDL.Func([IDL.Text], [Result_17], []),
  'getMyChallenge' : IDL.Func([], [Result_16], ['query']),
  'getMyClosedPositions' : IDL.Func([IDL.Nat], [IDL.Vec(Position)], ['query']),
  'getMyConsistencyScore' : IDL.Func([], [Result_15], ['query']),
  'getMyConsistencyScoreSummary' : IDL.Func([], [Result_15], ['query']),
  'getMyFundedAccount' : IDL.Func([], [Result_14], ['query']),
  'getMyInvestorBalance' : IDL.Func([], [Result_13], ['query']),
  'getMyOpenPositions' : IDL.Func([], [IDL.Vec(Position)], ['query']),
  'getMyPhaseStatus' : IDL.Func([], [Result_12], ['query']),
  'getMyProfile' : IDL.Func([], [Result_8], ['query']),
  'getMyTrades' : IDL.Func([IDL.Nat], [IDL.Vec(Trade)], ['query']),
  'getPayoutHistory' : IDL.Func(
      [IDL.Opt(IDL.Int), IDL.Opt(IDL.Int), IDL.Nat],
      [IDL.Vec(PayoutRecord)],
      ['query'],
    ),
  'getPayoutStats' : IDL.Func([], [Result_11], ['query']),
  'getPriceSnapshot' : IDL.Func(
      [IDL.Text, DexSource],
      [IDL.Opt(PriceCache)],
      ['query'],
    ),
  'getTargetOutcomes' : IDL.Func([IDL.Nat], [Result_5], ['query']),
  'getTraderAllocation' : IDL.Func([IDL.Principal], [Result_10], ['query']),
  'getTraderPublicProfile' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Opt(
          IDL.Record({
            'leaderboardEntry' : LeaderboardEntry,
            'recentTrades' : IDL.Vec(Trade),
            'consistencyHistory' : IDL.Vec(ConsistencyScore),
          })
        ),
      ],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'openPosition' : IDL.Func(
      [
        IDL.Text,
        TradeSide,
        IDL.Float64,
        IDL.Nat,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
      ],
      [Result_9],
      [],
    ),
  'overrideParams' : IDL.Func([AdminParams], [Result_7], []),
  'registerTrader' : IDL.Func([], [Result_8], []),
  'retryPendingWithdrawals' : IDL.Func([], [], []),
  'setAdminParams' : IDL.Func([IDL.Float64, RiskLevel], [Result_7], []),
  'setAdminPrincipal' : IDL.Func([IDL.Principal], [Result_6], []),
  'setPauseTrading' : IDL.Func([IDL.Bool], [Result_6], []),
  'setTargetOutcomes' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Float64, IDL.Float64],
      [Result_5],
      [],
    ),
  'suggestParamAdjustments' : IDL.Func([IDL.Nat], [Result_4], ['query']),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'triggerMonthlyReview' : IDL.Func([], [Result_3], []),
  'updateCohortParams' : IDL.Func(
      [IDL.Nat, IDL.Opt(PhaseParams), IDL.Opt(PhaseParams)],
      [Result_2],
      [],
    ),
  'validateTradeRequest' : IDL.Func(
      [IDL.Text, TradeSide, IDL.Float64, IDL.Nat],
      [ValidationResult],
      ['query'],
    ),
  'withdrawFromPool' : IDL.Func([IDL.Float64], [Result_1], []),
  'withdrawPlatformFees' : IDL.Func([IDL.Float64], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Result_6 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const DexSource = IDL.Variant({ 'icpSwap' : IDL.Null, 'sonic' : IDL.Null });
  const OrderStatus = IDL.Variant({
    'closed' : IDL.Null,
    'cancelled' : IDL.Null,
    'open' : IDL.Null,
    'filled' : IDL.Null,
    'liquidated' : IDL.Null,
    'pendingFill' : IDL.Null,
  });
  const TradeSide = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const Position = IDL.Record({
    'dex' : DexSource,
    'status' : OrderStatus,
    'exitTime' : IDL.Opt(IDL.Int),
    'traderId' : IDL.Principal,
    'currentPrice' : IDL.Float64,
    'direction' : TradeSide,
    'entryTime' : IDL.Int,
    'takeProfit' : IDL.Opt(IDL.Float64),
    'pair' : IDL.Text,
    'size' : IDL.Float64,
    'tradeId' : IDL.Nat,
    'realizedPnl' : IDL.Float64,
    'stopLoss' : IDL.Opt(IDL.Float64),
    'entryPrice' : IDL.Float64,
    'unrealizedPnl' : IDL.Float64,
    'simulatedFill' : IDL.Bool,
  });
  const Result_9 = IDL.Variant({ 'ok' : Position, 'err' : IDL.Text });
  const PhaseParams = IDL.Record({
    'timeLimitDays' : IDL.Nat,
    'maxTotalDrawdown' : IDL.Float64,
    'minTradingDays' : IDL.Nat,
    'profitTarget' : IDL.Float64,
    'maxDailyDrawdown' : IDL.Float64,
    'minConsistencyScore' : IDL.Float64,
  });
  const CohortParams = IDL.Record({
    'id' : IDL.Nat,
    'active' : IDL.Bool,
    'modifiedBy' : IDL.Opt(IDL.Principal),
    'name' : IDL.Text,
    'createdDate' : IDL.Int,
    'lastModified' : IDL.Int,
    'phase1' : PhaseParams,
    'phase2' : PhaseParams,
  });
  const Result_2 = IDL.Variant({ 'ok' : CohortParams, 'err' : IDL.Text });
  const Result_21 = IDL.Variant({
    'ok' : IDL.Record({ 'shares' : IDL.Nat, 'poolBalance' : IDL.Float64 }),
    'err' : IDL.Text,
  });
  const RiskLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const ChallengeStatus = IDL.Variant({
    'active' : IDL.Null,
    'failed' : IDL.Null,
    'passed' : IDL.Null,
    'paused' : IDL.Null,
  });
  const ChallengePhase = IDL.Variant({
    'notStarted' : IDL.Null,
    'funded' : IDL.Null,
    'phase1' : IDL.Null,
    'phase2' : IDL.Null,
  });
  const Challenge = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Int,
    'status' : ChallengeStatus,
    'currentBalance' : IDL.Float64,
    'trades' : IDL.Vec(IDL.Nat),
    'phase2StartTime' : IDL.Opt(IDL.Int),
    'perTradeLimitPct' : IDL.Float64,
    'dailyDrawdownLimitPct' : IDL.Float64,
    'fundedAllocation' : IDL.Opt(IDL.Float64),
    'traderPrincipal' : IDL.Principal,
    'phase1StartTime' : IDL.Opt(IDL.Int),
    'phase1EndTime' : IDL.Opt(IDL.Int),
    'startingBalance' : IDL.Float64,
    'targetProfitPct' : IDL.Float64,
    'phase' : ChallengePhase,
    'totalDrawdownLimitPct' : IDL.Float64,
    'phase2EndTime' : IDL.Opt(IDL.Int),
    'riskLevel' : RiskLevel,
    'consistencyScore' : IDL.Float64,
    'cohortId' : IDL.Opt(IDL.Nat),
  });
  const Result_16 = IDL.Variant({ 'ok' : Challenge, 'err' : IDL.Text });
  const ExecutionType = IDL.Variant({
    'simulated' : IDL.Null,
    'real' : IDL.Null,
  });
  const Trade = IDL.Record({
    'id' : IDL.Nat,
    'pnl' : IDL.Float64,
    'pair' : IDL.Text,
    'side' : TradeSide,
    'traderPrincipal' : IDL.Principal,
    'fillPrice' : IDL.Float64,
    'timestamp' : IDL.Int,
    'txHash' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Float64,
    'riskCheckPassed' : IDL.Bool,
    'executionType' : ExecutionType,
  });
  const Result_20 = IDL.Variant({ 'ok' : Trade, 'err' : IDL.Text });
  const AdminParams = IDL.Record({
    'challengeCheckIntervalSecs' : IDL.Nat,
    'pricePollingIntervalSecs' : IDL.Nat,
    'baseFee' : IDL.Float64,
    'maxTraderSharePct' : IDL.Float64,
    'perTradeLimitPct' : IDL.Float64,
    'dailyDrawdownLimitPct' : IDL.Float64,
    'baseAllocationAmount' : IDL.Float64,
    'updatedAt' : IDL.Int,
    'platformFeePct' : IDL.Float64,
    'investorPoolSharePct' : IDL.Float64,
    'traderBaseSharePct' : IDL.Float64,
    'targetProfitPct' : IDL.Float64,
    'slCheckIntervalSecs' : IDL.Nat,
    'tradingPaused' : IDL.Bool,
    'totalDrawdownLimitPct' : IDL.Float64,
    'riskLevel' : RiskLevel,
    'defaultPhase1' : PhaseParams,
    'defaultPhase2' : PhaseParams,
    'maxAllocationCap' : IDL.Float64,
    'performanceFee' : IDL.Float64,
  });
  const AuditEntry = IDL.Record({
    'principal' : IDL.Principal,
    'action' : IDL.Text,
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
  });
  const ConsistencyScore = IDL.Record({
    'traderId' : IDL.Principal,
    'activityScore' : IDL.Float64,
    'score' : IDL.Float64,
    'winRateScore' : IDL.Float64,
    'timestamp' : IDL.Int,
    'phase' : ChallengePhase,
    'profitDistScore' : IDL.Float64,
    'drawdownCtrlScore' : IDL.Float64,
  });
  const Result_19 = IDL.Variant({
    'ok' : IDL.Record({
      'investorCount' : IDL.Nat,
      'poolBalance' : IDL.Float64,
      'platformFeeBalance' : IDL.Float64,
      'totalShares' : IDL.Nat,
    }),
    'err' : IDL.Text,
  });
  const InvestorStats = IDL.Record({
    'totalAllocated' : IDL.Float64,
    'ytdReturn' : IDL.Float64,
    'traderCount' : IDL.Nat,
    'poolBalance' : IDL.Float64,
    'monthlyReturn' : IDL.Float64,
    'weeklyReturn' : IDL.Float64,
    'fundedTraderCount' : IDL.Nat,
    'avgConsistency' : IDL.Float64,
  });
  const Result_18 = IDL.Variant({ 'ok' : InvestorStats, 'err' : IDL.Text });
  const LeaderboardEntry = IDL.Record({
    'traderId' : IDL.Principal,
    'username' : IDL.Text,
    'lastTradeTime' : IDL.Int,
    'tradeCount' : IDL.Nat,
    'rank' : IDL.Nat,
    'profitPct' : IDL.Float64,
    'funded' : IDL.Bool,
    'phase' : ChallengePhase,
    'riskScore' : IDL.Float64,
    'consistencyScore' : IDL.Float64,
  });
  const PriceData = IDL.Record({
    'source' : IDL.Text,
    'pair' : IDL.Text,
    'timestamp' : IDL.Int,
    'price' : IDL.Float64,
  });
  const Result_17 = IDL.Variant({ 'ok' : PriceData, 'err' : IDL.Text });
  const Result_15 = IDL.Variant({ 'ok' : ConsistencyScore, 'err' : IDL.Text });
  const FundedAccount = IDL.Record({
    'traderId' : IDL.Principal,
    'monthsActive' : IDL.Nat,
    'accountBalance' : IDL.Float64,
    'performanceMultiplier' : IDL.Float64,
    'unrealizedPnl' : IDL.Float64,
    'nextReviewDate' : IDL.Int,
    'allocationCurrent' : IDL.Float64,
    'lastReviewDate' : IDL.Int,
    'allocationBase' : IDL.Float64,
  });
  const Result_14 = IDL.Variant({ 'ok' : FundedAccount, 'err' : IDL.Text });
  const Result_13 = IDL.Variant({
    'ok' : IDL.Record({
      'sharePrice' : IDL.Float64,
      'poolValue' : IDL.Float64,
      'shares' : IDL.Nat,
      'poolBalance' : IDL.Float64,
      'totalShares' : IDL.Nat,
    }),
    'err' : IDL.Text,
  });
  const Result_12 = IDL.Variant({
    'ok' : IDL.Record({
      'consistencyProgress' : IDL.Float64,
      'phase' : ChallengePhase,
      'timeRemainingDays' : IDL.Int,
      'profitProgress' : IDL.Float64,
    }),
    'err' : IDL.Text,
  });
  const TraderMode = IDL.Variant({
    'evaluation' : IDL.Null,
    'funded' : IDL.Null,
  });
  const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'trader' : IDL.Null });
  const TraderProfile = IDL.Record({
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'mode' : TraderMode,
    'role' : UserRole,
    'fundedAccount' : IDL.Opt(FundedAccount),
    'activeChallengeId' : IDL.Opt(IDL.Nat),
    'tenureMonths' : IDL.Nat,
    'totalPayouts' : IDL.Float64,
  });
  const Result_8 = IDL.Variant({ 'ok' : TraderProfile, 'err' : IDL.Text });
  const PayoutRecord = IDL.Record({
    'status' : IDL.Text,
    'traderId' : IDL.Principal,
    'closeTime' : IDL.Int,
    'consistencyBonus' : IDL.Float64,
    'platformShare' : IDL.Float64,
    'tenureBonus' : IDL.Float64,
    'traderPct' : IDL.Float64,
    'traderShare' : IDL.Float64,
    'investorShare' : IDL.Float64,
    'tradeId' : IDL.Nat,
    'profitAmount' : IDL.Float64,
  });
  const Result_11 = IDL.Variant({
    'ok' : IDL.Record({
      'totalPlatformRevenue' : IDL.Float64,
      'totalInvestorPayouts' : IDL.Float64,
      'totalTraderPayouts' : IDL.Float64,
      'platformFeeBalance' : IDL.Float64,
      'investorPoolBalance' : IDL.Float64,
    }),
    'err' : IDL.Text,
  });
  const PriceCache = IDL.Record({
    'ask' : IDL.Float64,
    'bid' : IDL.Float64,
    'dex' : DexSource,
    'last' : IDL.Float64,
    'pair' : IDL.Text,
    'volume' : IDL.Float64,
    'stale' : IDL.Bool,
    'timestamp' : IDL.Int,
  });
  const TargetOutcome = IDL.Record({
    'consistencyTarget' : IDL.Float64,
    'actualPassRate' : IDL.Float64,
    'lastUpdated' : IDL.Int,
    'passRateTarget' : IDL.Float64,
    'returnTarget' : IDL.Float64,
    'actualReturn' : IDL.Float64,
    'actualConsistency' : IDL.Float64,
    'cohortId' : IDL.Nat,
  });
  const Result_5 = IDL.Variant({ 'ok' : TargetOutcome, 'err' : IDL.Text });
  const AllocationChange = IDL.Record({
    'oldAllocation' : IDL.Float64,
    'traderId' : IDL.Principal,
    'reviewedBy' : IDL.Opt(IDL.Principal),
    'newAllocation' : IDL.Float64,
    'timestamp' : IDL.Int,
    'reason' : IDL.Text,
  });
  const Result_10 = IDL.Variant({
    'ok' : IDL.Record({
      'multiplier' : IDL.Float64,
      'base' : IDL.Float64,
      'history' : IDL.Vec(AllocationChange),
      'current' : IDL.Float64,
    }),
    'err' : IDL.Text,
  });
  const Result_7 = IDL.Variant({ 'ok' : AdminParams, 'err' : IDL.Text });
  const Result_4 = IDL.Variant({
    'ok' : IDL.Vec(
      IDL.Record({
        'metric' : IDL.Text,
        'suggested' : IDL.Float64,
        'current' : IDL.Float64,
        'reason' : IDL.Text,
      })
    ),
    'err' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const Result_3 = IDL.Variant({
    'ok' : IDL.Record({
      'reviewedCount' : IDL.Nat,
      'changes' : IDL.Vec(AllocationChange),
    }),
    'err' : IDL.Text,
  });
  const ValidationStatus = IDL.Variant({
    'conditional' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ValidationResult = IDL.Record({
    'status' : ValidationStatus,
    'reasons' : IDL.Vec(IDL.Text),
    'estimatedImpact' : IDL.Float64,
  });
  const Result_1 = IDL.Variant({
    'ok' : IDL.Record({
      'remainingShares' : IDL.Nat,
      'withdrawn' : IDL.Float64,
    }),
    'err' : IDL.Text,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Float64, 'err' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'cancelOrder' : IDL.Func([IDL.Nat], [Result_6], []),
    'closePosition' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Float64)], [Result_9], []),
    'createCohort' : IDL.Func(
        [IDL.Text, PhaseParams, PhaseParams],
        [Result_2],
        [],
      ),
    'depositToPool' : IDL.Func([IDL.Float64], [Result_21], []),
    'enterChallenge' : IDL.Func(
        [IDL.Float64, IDL.Float64, RiskLevel],
        [Result_16],
        [],
      ),
    'executeTrade' : IDL.Func(
        [IDL.Nat, IDL.Text, TradeSide, IDL.Float64],
        [Result_20],
        [],
      ),
    'forceChallenge' : IDL.Func(
        [IDL.Nat, ChallengeStatus, IDL.Text],
        [Result_16],
        [],
      ),
    'getAdminParams' : IDL.Func([], [AdminParams], ['query']),
    'getAllChallenges' : IDL.Func([], [IDL.Vec(Challenge)], ['query']),
    'getAllCohorts' : IDL.Func([], [IDL.Vec(CohortParams)], ['query']),
    'getAuditLog' : IDL.Func([IDL.Nat], [IDL.Vec(AuditEntry)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getConsistencyScoreHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ConsistencyScore)],
        ['query'],
      ),
    'getFundedTraderList' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'status' : IDL.Text,
              'traderId' : IDL.Principal,
              'username' : IDL.Text,
              'monthlyReturn' : IDL.Float64,
              'allocation' : IDL.Float64,
              'consistencyScore' : IDL.Float64,
            })
          ),
        ],
        ['query'],
      ),
    'getInvestorPoolSummary' : IDL.Func([], [Result_19], ['query']),
    'getInvestorStats' : IDL.Func([], [Result_18], ['query']),
    'getLeaderboard' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getLivePrice' : IDL.Func([IDL.Text], [Result_17], []),
    'getMyChallenge' : IDL.Func([], [Result_16], ['query']),
    'getMyClosedPositions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Position)],
        ['query'],
      ),
    'getMyConsistencyScore' : IDL.Func([], [Result_15], ['query']),
    'getMyConsistencyScoreSummary' : IDL.Func([], [Result_15], ['query']),
    'getMyFundedAccount' : IDL.Func([], [Result_14], ['query']),
    'getMyInvestorBalance' : IDL.Func([], [Result_13], ['query']),
    'getMyOpenPositions' : IDL.Func([], [IDL.Vec(Position)], ['query']),
    'getMyPhaseStatus' : IDL.Func([], [Result_12], ['query']),
    'getMyProfile' : IDL.Func([], [Result_8], ['query']),
    'getMyTrades' : IDL.Func([IDL.Nat], [IDL.Vec(Trade)], ['query']),
    'getPayoutHistory' : IDL.Func(
        [IDL.Opt(IDL.Int), IDL.Opt(IDL.Int), IDL.Nat],
        [IDL.Vec(PayoutRecord)],
        ['query'],
      ),
    'getPayoutStats' : IDL.Func([], [Result_11], ['query']),
    'getPriceSnapshot' : IDL.Func(
        [IDL.Text, DexSource],
        [IDL.Opt(PriceCache)],
        ['query'],
      ),
    'getTargetOutcomes' : IDL.Func([IDL.Nat], [Result_5], ['query']),
    'getTraderAllocation' : IDL.Func([IDL.Principal], [Result_10], ['query']),
    'getTraderPublicProfile' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Opt(
            IDL.Record({
              'leaderboardEntry' : LeaderboardEntry,
              'recentTrades' : IDL.Vec(Trade),
              'consistencyHistory' : IDL.Vec(ConsistencyScore),
            })
          ),
        ],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'openPosition' : IDL.Func(
        [
          IDL.Text,
          TradeSide,
          IDL.Float64,
          IDL.Nat,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
        ],
        [Result_9],
        [],
      ),
    'overrideParams' : IDL.Func([AdminParams], [Result_7], []),
    'registerTrader' : IDL.Func([], [Result_8], []),
    'retryPendingWithdrawals' : IDL.Func([], [], []),
    'setAdminParams' : IDL.Func([IDL.Float64, RiskLevel], [Result_7], []),
    'setAdminPrincipal' : IDL.Func([IDL.Principal], [Result_6], []),
    'setPauseTrading' : IDL.Func([IDL.Bool], [Result_6], []),
    'setTargetOutcomes' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Float64, IDL.Float64],
        [Result_5],
        [],
      ),
    'suggestParamAdjustments' : IDL.Func([IDL.Nat], [Result_4], ['query']),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'triggerMonthlyReview' : IDL.Func([], [Result_3], []),
    'updateCohortParams' : IDL.Func(
        [IDL.Nat, IDL.Opt(PhaseParams), IDL.Opt(PhaseParams)],
        [Result_2],
        [],
      ),
    'validateTradeRequest' : IDL.Func(
        [IDL.Text, TradeSide, IDL.Float64, IDL.Nat],
        [ValidationResult],
        ['query'],
      ),
    'withdrawFromPool' : IDL.Func([IDL.Float64], [Result_1], []),
    'withdrawPlatformFees' : IDL.Func([IDL.Float64], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };