/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminParams {
  'challengeCheckIntervalSecs' : bigint,
  'pricePollingIntervalSecs' : bigint,
  'baseFee' : number,
  'maxTraderSharePct' : number,
  'perTradeLimitPct' : number,
  'dailyDrawdownLimitPct' : number,
  'baseAllocationAmount' : number,
  'updatedAt' : bigint,
  'platformFeePct' : number,
  'investorPoolSharePct' : number,
  'traderBaseSharePct' : number,
  'targetProfitPct' : number,
  'slCheckIntervalSecs' : bigint,
  'tradingPaused' : boolean,
  'totalDrawdownLimitPct' : number,
  'riskLevel' : RiskLevel,
  'defaultPhase1' : PhaseParams,
  'defaultPhase2' : PhaseParams,
  'maxAllocationCap' : number,
  'performanceFee' : number,
}
export interface AllocationChange {
  'oldAllocation' : number,
  'traderId' : Principal,
  'reviewedBy' : [] | [Principal],
  'newAllocation' : number,
  'timestamp' : bigint,
  'reason' : string,
}
export interface AuditEntry {
  'principal' : Principal,
  'action' : string,
  'timestamp' : bigint,
  'details' : string,
}
export interface Challenge {
  'id' : bigint,
  'startTime' : bigint,
  'status' : ChallengeStatus,
  'currentBalance' : number,
  'trades' : Array<bigint>,
  'phase2StartTime' : [] | [bigint],
  'perTradeLimitPct' : number,
  'dailyDrawdownLimitPct' : number,
  'fundedAllocation' : [] | [number],
  'traderPrincipal' : Principal,
  'phase1StartTime' : [] | [bigint],
  'phase1EndTime' : [] | [bigint],
  'startingBalance' : number,
  'targetProfitPct' : number,
  'phase' : ChallengePhase,
  'totalDrawdownLimitPct' : number,
  'phase2EndTime' : [] | [bigint],
  'riskLevel' : RiskLevel,
  'consistencyScore' : number,
  'cohortId' : [] | [bigint],
}
export type ChallengePhase = { 'notStarted' : null } |
  { 'funded' : null } |
  { 'phase1' : null } |
  { 'phase2' : null };
export type ChallengeStatus = { 'active' : null } |
  { 'failed' : null } |
  { 'passed' : null } |
  { 'paused' : null };
export interface CohortParams {
  'id' : bigint,
  'active' : boolean,
  'modifiedBy' : [] | [Principal],
  'name' : string,
  'createdDate' : bigint,
  'lastModified' : bigint,
  'phase1' : PhaseParams,
  'phase2' : PhaseParams,
}
export interface ConsistencyScore {
  'traderId' : Principal,
  'activityScore' : number,
  'score' : number,
  'winRateScore' : number,
  'timestamp' : bigint,
  'phase' : ChallengePhase,
  'profitDistScore' : number,
  'drawdownCtrlScore' : number,
}
export type DexSource = { 'icpSwap' : null } |
  { 'sonic' : null };
export type ExecutionType = { 'simulated' : null } |
  { 'real' : null };
export interface FundedAccount {
  'traderId' : Principal,
  'monthsActive' : bigint,
  'accountBalance' : number,
  'performanceMultiplier' : number,
  'unrealizedPnl' : number,
  'nextReviewDate' : bigint,
  'allocationCurrent' : number,
  'lastReviewDate' : bigint,
  'allocationBase' : number,
}
export interface InvestorStats {
  'totalAllocated' : number,
  'ytdReturn' : number,
  'traderCount' : bigint,
  'poolBalance' : number,
  'monthlyReturn' : number,
  'weeklyReturn' : number,
  'fundedTraderCount' : bigint,
  'avgConsistency' : number,
}
export interface LeaderboardEntry {
  'traderId' : Principal,
  'username' : string,
  'lastTradeTime' : bigint,
  'tradeCount' : bigint,
  'rank' : bigint,
  'profitPct' : number,
  'funded' : boolean,
  'phase' : ChallengePhase,
  'riskScore' : number,
  'consistencyScore' : number,
}
export type OrderStatus = { 'closed' : null } |
  { 'cancelled' : null } |
  { 'open' : null } |
  { 'filled' : null } |
  { 'liquidated' : null } |
  { 'pendingFill' : null };
export interface PayoutRecord {
  'status' : string,
  'traderId' : Principal,
  'closeTime' : bigint,
  'consistencyBonus' : number,
  'platformShare' : number,
  'tenureBonus' : number,
  'traderPct' : number,
  'traderShare' : number,
  'investorShare' : number,
  'tradeId' : bigint,
  'profitAmount' : number,
}
export interface PhaseParams {
  'timeLimitDays' : bigint,
  'maxTotalDrawdown' : number,
  'minTradingDays' : bigint,
  'profitTarget' : number,
  'maxDailyDrawdown' : number,
  'minConsistencyScore' : number,
}
export interface Position {
  'dex' : DexSource,
  'status' : OrderStatus,
  'exitTime' : [] | [bigint],
  'traderId' : Principal,
  'currentPrice' : number,
  'direction' : TradeSide,
  'entryTime' : bigint,
  'takeProfit' : [] | [number],
  'pair' : string,
  'size' : number,
  'tradeId' : bigint,
  'realizedPnl' : number,
  'stopLoss' : [] | [number],
  'entryPrice' : number,
  'unrealizedPnl' : number,
  'simulatedFill' : boolean,
}
export interface PriceCache {
  'ask' : number,
  'bid' : number,
  'dex' : DexSource,
  'last' : number,
  'pair' : string,
  'volume' : number,
  'stale' : boolean,
  'timestamp' : bigint,
}
export interface PriceData {
  'source' : string,
  'pair' : string,
  'timestamp' : bigint,
  'price' : number,
}
export type Result = { 'ok' : number } |
  { 'err' : string };
export type Result_1 = {
    'ok' : { 'remainingShares' : bigint, 'withdrawn' : number }
  } |
  { 'err' : string };
export type Result_10 = {
    'ok' : {
      'multiplier' : number,
      'base' : number,
      'history' : Array<AllocationChange>,
      'current' : number,
    }
  } |
  { 'err' : string };
export type Result_11 = {
    'ok' : {
      'totalPlatformRevenue' : number,
      'totalInvestorPayouts' : number,
      'totalTraderPayouts' : number,
      'platformFeeBalance' : number,
      'investorPoolBalance' : number,
    }
  } |
  { 'err' : string };
export type Result_12 = {
    'ok' : {
      'consistencyProgress' : number,
      'phase' : ChallengePhase,
      'timeRemainingDays' : bigint,
      'profitProgress' : number,
    }
  } |
  { 'err' : string };
export type Result_13 = {
    'ok' : {
      'sharePrice' : number,
      'poolValue' : number,
      'shares' : bigint,
      'poolBalance' : number,
      'totalShares' : bigint,
    }
  } |
  { 'err' : string };
export type Result_14 = { 'ok' : FundedAccount } |
  { 'err' : string };
export type Result_15 = { 'ok' : ConsistencyScore } |
  { 'err' : string };
export type Result_16 = { 'ok' : Challenge } |
  { 'err' : string };
export type Result_17 = { 'ok' : PriceData } |
  { 'err' : string };
export type Result_18 = { 'ok' : InvestorStats } |
  { 'err' : string };
export type Result_19 = {
    'ok' : {
      'investorCount' : bigint,
      'poolBalance' : number,
      'platformFeeBalance' : number,
      'totalShares' : bigint,
    }
  } |
  { 'err' : string };
export type Result_2 = { 'ok' : CohortParams } |
  { 'err' : string };
export type Result_20 = { 'ok' : Trade } |
  { 'err' : string };
export type Result_21 = {
    'ok' : { 'shares' : bigint, 'poolBalance' : number }
  } |
  { 'err' : string };
export type Result_3 = {
    'ok' : { 'reviewedCount' : bigint, 'changes' : Array<AllocationChange> }
  } |
  { 'err' : string };
export type Result_4 = {
    'ok' : Array<
      {
        'metric' : string,
        'suggested' : number,
        'current' : number,
        'reason' : string,
      }
    >
  } |
  { 'err' : string };
export type Result_5 = { 'ok' : TargetOutcome } |
  { 'err' : string };
export type Result_6 = { 'ok' : null } |
  { 'err' : string };
export type Result_7 = { 'ok' : AdminParams } |
  { 'err' : string };
export type Result_8 = { 'ok' : TraderProfile } |
  { 'err' : string };
export type Result_9 = { 'ok' : Position } |
  { 'err' : string };
export type RiskLevel = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface TargetOutcome {
  'consistencyTarget' : number,
  'actualPassRate' : number,
  'lastUpdated' : bigint,
  'passRateTarget' : number,
  'returnTarget' : number,
  'actualReturn' : number,
  'actualConsistency' : number,
  'cohortId' : bigint,
}
export interface Trade {
  'id' : bigint,
  'pnl' : number,
  'pair' : string,
  'side' : TradeSide,
  'traderPrincipal' : Principal,
  'fillPrice' : number,
  'timestamp' : bigint,
  'txHash' : [] | [string],
  'quantity' : number,
  'riskCheckPassed' : boolean,
  'executionType' : ExecutionType,
}
export type TradeSide = { 'buy' : null } |
  { 'sell' : null };
export type TraderMode = { 'evaluation' : null } |
  { 'funded' : null };
export interface TraderProfile {
  'principal' : Principal,
  'username' : string,
  'mode' : TraderMode,
  'role' : UserRole,
  'fundedAccount' : [] | [FundedAccount],
  'activeChallengeId' : [] | [bigint],
  'tenureMonths' : bigint,
  'totalPayouts' : number,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'trader' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface ValidationResult {
  'status' : ValidationStatus,
  'reasons' : Array<string>,
  'estimatedImpact' : number,
}
export type ValidationStatus = { 'conditional' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'cancelOrder' : ActorMethod<[bigint], Result_6>,
  'closePosition' : ActorMethod<[bigint, [] | [number]], Result_9>,
  'createCohort' : ActorMethod<[string, PhaseParams, PhaseParams], Result_2>,
  'depositToPool' : ActorMethod<[number], Result_21>,
  'enterChallenge' : ActorMethod<[number, number, RiskLevel], Result_16>,
  'executeTrade' : ActorMethod<[bigint, string, TradeSide, number], Result_20>,
  'forceChallenge' : ActorMethod<[bigint, ChallengeStatus, string], Result_16>,
  'getAdminParams' : ActorMethod<[], AdminParams>,
  'getAllChallenges' : ActorMethod<[], Array<Challenge>>,
  'getAllCohorts' : ActorMethod<[], Array<CohortParams>>,
  'getAuditLog' : ActorMethod<[bigint], Array<AuditEntry>>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getConsistencyScoreHistory' : ActorMethod<[bigint], Array<ConsistencyScore>>,
  'getFundedTraderList' : ActorMethod<
    [],
    Array<
      {
        'status' : string,
        'traderId' : Principal,
        'username' : string,
        'monthlyReturn' : number,
        'allocation' : number,
        'consistencyScore' : number,
      }
    >
  >,
  'getInvestorPoolSummary' : ActorMethod<[], Result_19>,
  'getInvestorStats' : ActorMethod<[], Result_18>,
  'getLeaderboard' : ActorMethod<
    [string, bigint, bigint],
    Array<LeaderboardEntry>
  >,
  'getLivePrice' : ActorMethod<[string], Result_17>,
  'getMyChallenge' : ActorMethod<[], Result_16>,
  'getMyClosedPositions' : ActorMethod<[bigint], Array<Position>>,
  'getMyConsistencyScore' : ActorMethod<[], Result_15>,
  'getMyConsistencyScoreSummary' : ActorMethod<[], Result_15>,
  'getMyFundedAccount' : ActorMethod<[], Result_14>,
  'getMyInvestorBalance' : ActorMethod<[], Result_13>,
  'getMyOpenPositions' : ActorMethod<[], Array<Position>>,
  'getMyPhaseStatus' : ActorMethod<[], Result_12>,
  'getMyProfile' : ActorMethod<[], Result_8>,
  'getMyTrades' : ActorMethod<[bigint], Array<Trade>>,
  'getPayoutHistory' : ActorMethod<
    [[] | [bigint], [] | [bigint], bigint],
    Array<PayoutRecord>
  >,
  'getPayoutStats' : ActorMethod<[], Result_11>,
  'getPriceSnapshot' : ActorMethod<[string, DexSource], [] | [PriceCache]>,
  'getTargetOutcomes' : ActorMethod<[bigint], Result_5>,
  'getTraderAllocation' : ActorMethod<[Principal], Result_10>,
  'getTraderPublicProfile' : ActorMethod<
    [Principal],
    [] | [
      {
        'leaderboardEntry' : LeaderboardEntry,
        'recentTrades' : Array<Trade>,
        'consistencyHistory' : Array<ConsistencyScore>,
      }
    ]
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'openPosition' : ActorMethod<
    [string, TradeSide, number, bigint, [] | [number], [] | [number]],
    Result_9
  >,
  'overrideParams' : ActorMethod<[AdminParams], Result_7>,
  'registerTrader' : ActorMethod<[], Result_8>,
  'retryPendingWithdrawals' : ActorMethod<[], undefined>,
  'setAdminParams' : ActorMethod<[number, RiskLevel], Result_7>,
  'setAdminPrincipal' : ActorMethod<[Principal], Result_6>,
  'setPauseTrading' : ActorMethod<[boolean], Result_6>,
  'setTargetOutcomes' : ActorMethod<[bigint, number, number, number], Result_5>,
  'suggestParamAdjustments' : ActorMethod<[bigint], Result_4>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'triggerMonthlyReview' : ActorMethod<[], Result_3>,
  'updateCohortParams' : ActorMethod<
    [bigint, [] | [PhaseParams], [] | [PhaseParams]],
    Result_2
  >,
  'validateTradeRequest' : ActorMethod<
    [string, TradeSide, number, bigint],
    ValidationResult
  >,
  'withdrawFromPool' : ActorMethod<[number], Result_1>,
  'withdrawPlatformFees' : ActorMethod<[number], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];